model: 'XCLIP_DeMamba_4'
tuning_mode: 'sft'
task: 'many2many'

save_dir: '../../MSLoc_data/DeMamba/results/demamba_4'

max_epoch: 10
bath_per_epoch: 1000

train_batch_size: 32
val_batch_size: 32
num_workers: 32
lr: 0.000001


# Path are relative to MSLoc/DeMamba (the working dir for train.py / eval.py)
train_json_path: '../../MSLoc_data/data/Tasle-CoT-10K/annos/train_all_1209.json'
test_json_path: '../../MSLoc_data/data/Tasle-CoT-10K/annos/train_all_1209.json'
dataset_base_path: '../../MSLoc_data/data/Tasle-CoT-10K/video_frames'
window_length: 2.0
frames_per_window: 8
mode: 'four_class'
transform_config: {
  crop_youku: True
}
